export enum MobileScreenEnum {
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  DASHBOARD_SCREEN = 'DASHBOARD_SCREEN',
  INTRO_SCREEN = 'INTRO_SCREEN',
  ORDER_SCREEN = 'ORDER_SCREEN',
  CREATE_ORDER_SCREEN = 'CREATE_ORDER_SCREEN',
  CREATE_ORDER_SCREEN_1 = 'CREATE_ORDER_SCREEN_1',
  PERFORM_SCREEN = 'PERFORM_SCREEN',
  PAYMENT_SCREEN = 'PAYMENT_SCREEN',
  COMPLETE_ORDER_SCREEN = 'COMPLETE_ORDER_SCREEN',
}
